---
title: "Leaders' views"
author: "Nick Parkinson"
date: "18 July 2024"
format: 
  html:
    css: .formatting/grattan-style.css
    theme: lumen
    highlight: pygments
    toc: true
    toc_depth: 2
    number_sections: yes
    df_print: kable
    fig-height: 5.7
    fig-width: 8.75
    fig-cap-location: top
    fig-dpi: 300
lightbox: true
execute:
  echo: false
  warning: false
  freeze: auto
editor: visual
editor_options: 
  chunk_output_type: console
---

```{r}
#| label: set-up
#| include: false

source("R/globals.R")
load(file = "data/clean_survey.Rdata")
load(file = "data/raked_survey.Rdata")
```

## How do leaders feel?

```{r}
#| label: leaders_views
#| fig.height: 9
leader_view_labels <- clean_survey |> 
  select(starts_with("Q30")) |> 
  var_labels() |> 
  get_label() |> 
  str_replace_all(c("questions_for_leaders - " = "",
                  "\\s*\\([^\\)]+\\)" = ""))

leaders_views_df <- survey_data_raked |>
  select(starts_with("Q30")) |> 
  mutate(across(starts_with("Q30"), ~ case_when(
    . == "Agree" ~ T,
    . == "Strongly agree" ~ T,
    is.na(.) ~ NA,
    .default = F
  ))) |> 
    summarise(across(everything(),
                     list(pct = ~survey_mean(.x, na.rm = T, vartype = "ci", level = 0.9),
                          n = ~sum(!is.na(.x)))
                   )
            ) |> 
   pivot_longer(
   cols = everything(),
    names_to = c("question", ".value"),
    names_pattern = "(Q30_\\d+)_(.+)"
  ) |> 
  mutate(label = leader_view_labels)

leaders_views_df |> 
  ggplot(aes(x = factor(str_wrap(label, 40)) |> fct_reorder(pct),
             y = pct, 
             ymin = pct_low, 
             ymax = pct_upp)) +
  geom_col() +
  geom_errorbar(color = grattan_black,
                width = .2) +
  coord_flip() +
  # theme and labels
  theme_grattan(flipped = T,
                base_size = 14) +
  grattan_y_continuous(labels = percent) +
  labs(title = "Leaders feel ill-supported by government to improve maths teaching in their schools",
       subtitle = "Percent of leaders who agree or strongly agree (with 90 per cent confidence interval)",
       x = NULL, y = NULL,
       caption = glue("Notes: Total responses to statements varied by statement between {min(leaders_views_df$n) |> comma()} and {max(leaders_views_df$n) |> comma()}. {source_caption}"))
  
```

Check results by state and territory.

```{r}
leaders_views_state_and_territory <- survey_data_raked |>
  select(state_territory, Q30_5, Q30_6) |> 
  mutate(across(starts_with("Q30"), ~ case_when(
    . == "Agree" ~ T,
    . == "Strongly agree" ~ T,
    is.na(.) ~ NA,
    .default = F
  ))) |> 
  group_by(state_territory) |> 
    summarise(across(everything(),
                     list(pct = ~survey_mean(.x, na.rm = T, vartype = "ci", level = 0.9),
                          n = ~sum(!is.na(.x)))
                   )
            ) |> 
   pivot_longer(
   cols = !state_territory,
    names_to = c("question", ".value"),
    names_pattern = "(Q30_\\d+)_(.+)"
  ) |> 
  mutate(label = rep(leader_view_labels[5:6], 8)) 

sample_sizes <- leaders_views_state_and_territory |> 
  mutate(state_territory = fct_reorder(state_territory, -pct)) |> 
  group_by(state_territory) |> 
  summarise(min = min(n)) |> 
  transmute(sample_sizes = str_c(state_territory, min, sep = " - ")) |>
  pull(sample_sizes) |> 
  str_flatten_comma(" and ")

leaders_views_state_and_territory |> 
  ggplot(aes(x = fct_reorder(state_territory, pct),
             y = pct, 
             ymin = pct_low, 
             ymax = pct_upp, 
             fill = label, 
             group = label)) +
  geom_linerange(color = rep(c(grattan_red4, grattan_orange4), 8),
                linewidth = 18/.pt, 
                position = position_dodge(0.9)) +
  geom_point(position = position_dodge(0.9), size = 18/.pt, color = rep(c(grattan_red, grattan_orange), 8)) +
  geom_text(aes(label = percent(pct, 1)), 
            position = position_dodge(0.9), size = 14/.pt, 
            vjust = -.75, 
            hjust = 0.4) +
  coord_flip() +
  geom_richlegend(aes(label =  gsub("\\n", 
                                    "<br>", 
                                    str_wrap(label, 30)), 
                      color = fct_rev(label)), 
                  legend.position = c(1, 0.6), 
                  size = 14/.pt) +
  # theme and labels
  theme_grattan(flipped = T,
                base_size = 14) +
  grattan_y_continuous(labels = percent, limits = c(-.2, 1)) +
  labs(title = "The clarity of advice is a challenge across states and territories",
       subtitle = "Percent of leaders who agree or strongly agree (with 90 per cent confidence interval)",
       x = NULL, y = NULL,
       caption = glue("Notes: Total responses from each state and territory were: {sample_sizes} .\n{source_caption}"))
```

## To what extent are teachers' hesistant about upper primary?

```{r}
#| label: hesitations-about-upper-primary

clean_survey |> 
  drop_na(Q31) |> 
  tabulator::tab(Q31) |> 
  select(-cum_prop) |> 
  mutate(
    Q31 = factor(
           Q31, 
           levels = c(
             "No teachers",
             "Some teachers",
             "About half of teachers", 
             "Most teachers", 
             "All teachers"
         )),
    prop = percent(prop, 0.1)) |> 
  arrange(Q31) |> 
  kable(align = "lrr")
```

## 
