---
title: "Schools' practices"
author: "Nick Parkinson"
date: "18 July 2024"
format: 
  html:
    css: .formatting/grattan-style.css
    theme: lumen
    highlight: pygments
    toc: true
    toc_depth: 2
    number_sections: yes
    df_print: kable
    fig-height: 5.7
    fig-width: 8.75
    fig-cap-location: top
    fig-dpi: 300
lightbox: auto
execute:
  echo: false
  warning: false
  freeze: auto
editor: visual
editor_options: 
  chunk_output_type: console
---

```{r}
#| label: set-up
#| include: false

source("R/globals.R")
load(file = "data/clean_survey.Rdata")
load(file = "data/raked_survey.Rdata")
```

## How do schools schedule maths?

```{r}
#| label: maths-scheduling-approach
survey_data_raked |> 
  drop_na(Q24) |> 
  group_by(Q24) |> 
  summarise(pct = survey_mean(vartype = "ci", level = 0.9, na.rm = T)) |>
  drop_na() |> 
  arrange(-pct) |> 
  mutate(across(starts_with("pct"), ~percent(.x, 0.1))) |> 
  kable(align = "lrrr", col.names = c("Approach to scheduling maths", "%", "90% CI (lower)", "90% CI (upper)"))

  
```

```{r}
#| label: hours_of_maths
hours_taught_df <- 
  survey_data_raked |> 
  mutate(hours_taught = coalesce(clean_survey$Q25, clean_survey$Q26)) |> 
  drop_na(hours_taught) |> 
  group_by(hours_taught) |> 
  summarise(pct = survey_mean(na.rm = T, vartype = "ci", level = 0.9),
            n = n()) |> 
  drop_na(hours_taught) |> 
  mutate(n = sum(n),
         hours_taught = str_extract(hours_taught, "\\d+\\.?\\d*"),
         hours_taught = if_else(row_number() == 1, ">10",
                     if_else(row_number() == n(), "<2", 
                             as.character(hours_taught)))) |> 
  slice(c(n(), 2:(n() - 1), 1)) |> 
  mutate(hours_taught = factor(hours_taught, hours_taught))

hours_taught_df |> 
  ggplot(aes(x = hours_taught, y = pct, ymax = pct_upp, ymin = pct_low)) +
  geom_col() + 
  geom_errorbar(color = "black", width = .2) +
  # theme and labels
  theme_grattan(base_size = 14) + 
  grattan_colour_manual() +
  grattan_fill_manual() +
  grattan_y_continuous(labels = percent) + 
  labs(title = "Most schools teach between 4 and 5 hours of maths a week",
       subtitle = "Percentage of teachers and principals who selected each response (with 90% confidence intervals)",
       x = "Timetabled hours of maths per week", y = NULL,
       caption = glue("Note: Total number of responses is {min(hours_taught_df$n) |> comma()}. {source_caption}"))
```

## School practices

```{r}
#| label: school_practices
#| fig.height: 11
school_practice_labels <- clean_survey |> 
  select(starts_with("Q27")) |> 
  var_labels() |> 
  get_label() |> 
  str_replace_all(c("school_practices - " = "",
                  "\\s*\\([^\\)]+\\)" = ""))

school_practice_df <- survey_data_raked |>
 select(starts_with(c("Q27"))) |> 
  mutate(across(starts_with("Q27"), ~ case_when(
    . == "Agree" ~ T,
    . == "Strongly agree" ~ T,
    is.na(.) ~ NA,
    .default = F
  )))

school_practice_df <- 
  school_practice_df |> 
  summarise(across(everything(),
                     list(pct = ~survey_mean(.x, na.rm = T, vartype = "ci", level = 0.9),
                          n = ~sum(!is.na(.x)))
                   )
            ) |> 
   pivot_longer(
   cols = everything(),
    names_to = c("question", ".value"),
    names_pattern = "(Q27_\\d+)_(.+)"
  ) |> 
  mutate(label = school_practice_labels)

school_practice_df |> 
  ggplot(aes(x = factor(str_wrap(label, 40)) |> fct_reorder(pct),
             y = pct, 
             ymin = pct_low, 
             ymax = pct_upp)) +
  geom_col() +
  geom_errorbar(color = grattan_black,
                width = .2) +
  coord_flip() +
  # theme and labels
  theme_grattan(flipped = T,
                base_size = 14) +
  grattan_y_continuous(labels = percent) +
  labs(title = "Many schools do not yet have a systematic approach to maths instruction in place",
       subtitle = "Percent of teachers who agree or strongly agree (with 90 per cent confidence interval)",
       x = NULL, y = NULL,
       caption = glue("Notes: Total responses to statements varied by statement between {min(school_practice_df$n) |> comma()} and {max(school_practice_df$n) |> comma()}. {source_caption}"))
```

We can see how these results differ by ses

```{r}
#| label: school_practices_ses
#| fig.height: 11

school_practices_by_ses <- survey_data_raked |>
 select(starts_with(c("ses", "Q27"))) |> 
  mutate(across(starts_with("Q27"), ~ case_when(
    . == "Agree" ~ T,
    . == "Strongly agree" ~ T,
    is.na(.) ~ NA,
    .default = F
  ))) |> 
  mutate(ses = factor(ses, levels = c(
                           "Mostly disadvantaged", 
                           "A fairly even mix of advantaged and disadvantaged students", 
                           "Mostly advantaged")
                           ))

# Playing around with statistical tests

# svyranktest(Q27_1 ~ ses, survey_data_raked, na.rm = T, test= "KruskalWallis")
# 
# svychisq(~Q27_1 + ses, school_practices_by_ses)
# 
# model <- svyglm(Q27_1~ses, school_practice_df)
# summary(model)

# Simple two-sample t-tests
# Will need to soft-code and automate this
# survey::svyttest(Q27_1 ~ ses=="Mostly advantaged", subset(school_practices_by_ses, ses != "A fairly even mix of advantaged and disadvantaged students")) # Significant
# survey::svyttest(Q27_2 ~ ses=="Mostly advantaged", subset(school_practices_by_ses, ses != "A fairly even mix of advantaged and disadvantaged students"))
# survey::svyttest(Q27_3 ~ ses=="Mostly advantaged", subset(school_practices_by_ses,ses != "A fairly even mix of advantaged and disadvantaged students"))
# survey::svyttest(Q27_4 ~ ses=="Mostly advantaged", subset(school_practices_by_ses, ses != "A fairly even mix of advantaged and disadvantaged students"))
# survey::svyttest(Q27_5 ~ ses=="Mostly advantaged", subset(school_practices_by_ses, ses != "A fairly even mix of advantaged and disadvantaged students"))
# survey::svyttest(Q27_6 ~ ses=="Mostly advantaged", subset(school_practices_by_ses, ses != "A fairly even mix of advantaged and disadvantaged students")) # Significant
# survey::svyttest(Q27_7 ~ ses=="Mostly advantaged", subset(school_practices_by_ses, ses != "A fairly even mix of advantaged and disadvantaged students")) # Significant


school_practices_by_ses_df <- 
school_practices_by_ses |> 
group_by(ses) |> 
summarise(across(starts_with("Q27"),
                     list(pct = ~survey_mean(.x, na.rm = T, vartype = "ci", level = 0.9),
                          n = ~sum(!is.na(.x)))
                   )
            )  |> 
  pivot_longer(
   cols = !ses,
    names_to = c("question", ".value"),
    names_pattern = "(Q27_\\d+)_(.+)"
  ) |> 
  drop_na() |> 
  mutate(label = rep(school_practice_labels, 3), 
         significant = rep(c("*", "", "", "", "", "*", "*"), 3), 
         label = paste0(label, significant)) 
  
school_practices_by_ses_df |> 
  ggplot(aes(x = factor(str_wrap(label, 40)) |> fct_reorder(pct),
             y = pct, 
             ymin = pct_low, 
             ymax = pct_upp,
             fill = fct_rev(ses), 
             )) +
  geom_col(position = "dodge") +
  geom_errorbar(color = grattan_black,
                width = .2, position = position_dodge(0.9)) +
  coord_flip() +
  # theme and labels
  theme_grattan(flipped = T,
                base_size = 14) +
  theme(plot.subtitle = ggtext::element_markdown()) +
  grattan_y_continuous(labels = percent, expand_top = 0.4) +
  # geom_richlegend(aes(label = ses, color = ses), legend.position = "bottomright", vjust = 0) +
  labs(title = "Challenges exist in all schools, but especially in disadvantaged schools",
       subtitle = glue("Percent of teachers who agree or strongly agree (with 90 per cent confidence interval)<br/>in schools with {colour_text(grattan_red, 'mostly disadvantaged')}, {colour_text(grattan_orange, 'an even mix')}, or {colour_text(grattan_yellow, 'mostly advantaged')} students"),
       x = NULL, y = NULL,
       caption = glue("Notes: Total responses to statements by group were at least {school_practices_by_ses_df |> group_by(ses) |> summarise(min = min(n)) |> pull(min) |> paste(collapse = ', ')} respectively. Statements marked with an asterisk mean that there was a significant difference\n(at the 90 per cent confidence interval) between the porportion of teachers in disavantaged and advantaged schools who agreed or strongly agreed with the statement.\n{source_caption}"))



```

## Perceptions of colleagues' content knowledge

```{r}
#| label: teacher-confidence
#| fig.height: 8
teacher_knowledge_labels <- clean_survey |> 
  select(starts_with("Q28")) |> 
  var_labels() |> 
  get_label() |> 
  str_replace_all(c("teachers_subject_knowledge - " = "",
                  "\\s*\\([^\\)]+\\)" = ""))

teacher_knowledge_df <- clean_survey |>
  select(starts_with("Q28")) |> 
  pivot_longer(everything(), names_to = "question", values_to = "response") |> 
  drop_na(response) |> 
  group_by(question, response) |> 
  summarise(n = n()) |> 
  group_by(question) |> 
  mutate(prop = n/sum(n),
         sample_size = sum(n)) |> 
  ungroup() |> 
  mutate(label = rep(teacher_knowledge_labels, each = 5), 
         response = factor(
           response, 
           levels = c(
             "No teacher",
             "Some teachers",
             "About half of teachers", 
             "Most teachers", 
             "All teachers"
         )))

teacher_knowledge_df |> 
  ggplot(aes(x = factor(str_wrap(label, 40)),
             y = prop,
             fill = fct_rev(response))) +
  geom_col() +
  coord_flip() +
  # theme and labels
  theme_grattan(flipped = T,
                base_size = 14,
                legend = "bottom") +
  theme(legend.location = "plot") +
  grattan_y_continuous(labels = percent) +
  guides(fill = guide_legend(reverse = TRUE)) +
  labs(title = "Many teachers feel that fewer than half of their colleagues could teach Year 6 maths",
       subtitle = "Percent of teachers who gave each response",
       x = NULL, y = NULL,
       caption = glue("Notes: Total responses to statements varied by statement between {min(teacher_knowledge_df$sample_size) |> comma()} and {max(teacher_knowledge_df$sample_size) |> comma()}. {source_caption}"))
  
```

