---
title: "Teachers' attitudes towards maths"
author: "Nick Parkinson"
date: "18 July 2024"
format: 
  html:
    css: .formatting/grattan-style.css
    theme: lumen
    highlight: pygments
    toc: true
    toc_depth: 2
    number_sections: yes
    df_print: kable
    fig-height: 5.7
    fig-width: 8.75
    fig-cap-location: top
    fig-dpi: 300
lightbox: true
execute:
  echo: false
  warning: false
  cache: true
  freeze: auto
editor: visual
editor_options: 
  chunk_output_type: console
---

```{r}
#| label: set-up
#| include: false

source("R/globals.R")
load(file = "data/clean_survey.Rdata")
```

## How many teachers studied maths in Year 12?

```{r}
#| label: y-12-maths
clean_survey |> 
  drop_na(Q13) |> 
  tabulator::tab(Q13) |> 
  select(-cum_prop) |> 
  mutate(prop = percent(prop, 1),
         Question = factor(Q13, 
                           levels = c(
                             "No maths", 
                             "Foundational maths", 
                             "Lower intermediate maths", 
                             "Upper intermediate maths", 
                             "Advanced maths"
                           )), .before = everything()) |> 
  arrange(Question) |> 
  select(-Q13) |> 
  kable(align = "lrr")
```

## How many teachers studied maths in higher education?

```{r}
#| label: uni-maths
clean_survey |> 
  drop_na(Q14) |> 
  tabulator::tab(Q14) |> 
  select(-cum_prop) |> 
  mutate(prop = percent(prop, 1)) |> 
  kable(align = "lrr")
```

## How confident do teachers feel about maths?

```{r}
#| label: teacher-confidence
#| fig.height: 8
teacher_confidence_labels <- clean_survey |> 
  select(Q38_1:Q38_8) |> 
  var_labels() |> 
  get_label() |> 
  str_replace_all(c("attitudes_to_maths - " = "",
                  "\\s*\\([^\\)]+\\)" = ""))

teacher_confidence_df <- clean_survey |>
  select(Q38_1:Q38_8) |> 
  mutate(across(starts_with("Q38"), ~ case_when(
    . == "Agree" ~ T,
    . == "Strongly agree" ~ T,
    is.na(.) ~ NA,
    .default = F
  ))) |> 
  pivot_longer(everything(), names_to = "question", values_to = "response") |> 
  group_by(question) |> 
  summarise(mean = mean(response, na.rm = T), 
            se = sd(response, na.rm = T)  / sqrt(sum(!is.na(response))),
            n = sum(!is.na(response))) |> 
  mutate(label = teacher_confidence_labels)

teacher_confidence_df |> 
  ggplot(aes(x = factor(str_wrap(label, 40)) |> fct_reorder(mean),
             y = mean, 
             ymin = mean - 1.65 * se, 
             ymax = mean + 1.65 * se)) +
  geom_col() +
  geom_errorbar(color = grattan_black,
                width = .2) +
  coord_flip() +
  # theme and labels
  theme_grattan(flipped = T,
                base_size = 14) +
  grattan_y_continuous(labels = percent) +
  labs(title = "Most primary teachers feel confident to teach maths",
       subtitle = "Percent of teachers who agree or strongly agree (with 90 per cent confidence interval)",
       x = NULL, y = NULL,
       caption = glue("Notes: Total responses to statements varied by statement between {min(teacher_confidence_df$n) |> comma()} and {max(teacher_confidence_df$n) |> comma()}. {source_caption}"))
  
```

## How anxious do teachers feel about maths?

```{r}
#| label: teacher-anxiety

teacher_anxiety_labels <- clean_survey |> 
  select(Q40_1:Q40_4) |> 
  var_labels() |> 
  get_label() |> 
  str_replace("maths_anxiety - ", "")

teacher_anxiety_df <- clean_survey |>
  select(Q40_1:Q40_4) |> 
  mutate(across(starts_with("Q40"), ~ case_when(
    . == "Agree" ~ T,
    . == "Strongly agree" ~ T,
    is.na(.) ~ NA,
    .default = F
  ))) |> 
  pivot_longer(everything(), names_to = "question", values_to = "response") |> 
  group_by(question) |> 
  summarise(mean = mean(response, na.rm = T), 
            se = sd(response, na.rm = T)  / sqrt(sum(!is.na(response))),
            n = sum(!is.na(response))) |> 
  mutate(label = teacher_anxiety_labels)

teacher_anxiety_df |> 
  ggplot(aes(x = factor(str_wrap(label, 40)) |> fct_reorder(mean),
             y = mean, 
             ymin = mean - 1.65 * se, 
             ymax = mean + 1.65 * se)) +
  geom_col() +
  geom_errorbar(color = grattan_black,
                width = .2) +
  coord_flip() +
  # theme and labels
  theme_grattan(flipped = T,
                base_size = 14) +
  grattan_y_continuous(labels = percent) +
  labs(title = "A minority of teachers feel anxious about teaching maths",
       subtitle = "Percent of teachers who agree or strongly agree (with 90 per cent confidence interval)",
       x = NULL, y = NULL,
       caption = glue("Notes: Total responses to statements varied by statement between {min(teacher_anxiety_df$n) |> comma()} and {max(teacher_anxiety_df$n) |>  comma()}. {source_caption}"))
```

## How does anxiety compare by teacher and school characteristics?

```{r}
eacher_anxiety_df_for_regressions <-
  clean_survey |>
  mutate(across(starts_with("Q40"), ~ case_when(
    . == "Agree" ~ T,
    . == "Strongly agree" ~ T,
    is.na(.) ~ NA,
    .default = F
  ))) |>
  mutate(ses = relevel(factor(Q20), ref = "Mostly advantaged"))
```


### Teacher gender
```{r}
#| label: teacher_anxiety_by_gender
model <- glm(Q40_1 ~ sex_gender,
  family = "binomial",
  data = teacher_anxiety_df_for_regressions
)

summary(model)

model <- glm(Q40_2 ~ sex_gender,
  family = "binomial",
  data = teacher_anxiety_df_for_regressions
)

summary(model)

model <- glm(Q40_3 ~ sex_gender,
  family = "binomial",
  data = teacher_anxiety_df_for_regressions
)

summary(model)

glue('Being male is associated with a reduction of {percent(1 - exp(model$coefficients[[2]]))} in odds of agreeing with the statement "{teacher_anxiety_labels[3]}"')


model <- glm(Q40_4 ~ sex_gender,
  family = "binomial",
  data = teacher_anxiety_df_for_regressions
)

summary(model)

glue('Being male is associated with a reduction of {percent(1 - exp(model$coefficients[[2]]))} in odds of agreeing with the statement "{teacher_anxiety_labels[4]}"')
```


### School-level advantage
```{r}
#| label: teacher-anxiety-by-ses

# By SES

model <- glm(Q40_1 ~ ses,
  family = "binomial",
  data = teacher_anxiety_df_for_regressions
)

summary(model)

model <- glm(Q40_2 ~ ses,
  family = "binomial",
  data = teacher_anxiety_df_for_regressions
)

summary(model)

model <- glm(Q40_3 ~ ses,
  family = "binomial",
  data = teacher_anxiety_df_for_regressions
)

summary(model)

model <- glm(Q40_4 ~ ses,
  family = "binomial",
  data = teacher_anxiety_df_for_regressions
)

summary(model)

```

