name: deploy-website

on:
  push:
  schedule:
    - cron: '0 */2 * * *'

jobs:
  update-website:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Load packages
        uses: r-lib/actions/setup-renv@v2

      - name: Cache R packages
        uses: actions/cache@v4 # Updated to the latest version
        with:
          path: ~/.cache/R
          key: ${{ runner.os }}-r-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-r-

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
